### ISSUE TITLE
Caused by android.os.DeadObjectException

### ISSUE THREAD

**Issue by AliKhoshraftar** [cafebazaar/Poolakey#26]
**Describe the bug**
We are using this library in our application. so few of our users have billing problem with this.
The error is : Caused by android.os.DeadObjectException with detail : 

`android.os.BinderProxy.transactNative (BinderProxy.java)
android.os.BinderProxy.transact (BinderProxy.java:527)
com.android.vending.billing.IInAppBillingService$Stub$Proxy.isBillingSupported (IInAppBillingService.java:26)
com.phelat.poolakey.BillingConnection.isPurchaseTypeSupported (BillingConnection.java:11)
com.phelat.poolakey.BillingConnection.onServiceConnected (BillingConnection.java:8)
android.app.LoadedApk$ServiceDispatcher.doConnected (LoadedApk.java:2067)
android.app.LoadedApk$ServiceDispatcher$RunConnection.run (LoadedApk.java:2099)
android.os.Handler.handleCallback (Handler.java:883)
android.os.Handler.dispatchMessage (Handler.java:100)
android.os.Looper.loop (Looper.java:237)
android.app.ActivityThread.main (ActivityThread.java:7811)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1068)`

**Versions**
- 1.0.0-alpha4
- API Versions : 26, 27 ,28, 29

**Comment by DHosseiny** [comment]
Fixed in #34

**Comment by DHosseiny** [comment]
Fixed in #34. We can close this. @PHELAT

**Comment by PHELAT** [comment]
Thanks for reporting this issue. It's now fixed in `1.0.0-alpha09` release of this library.
