### ISSUE TITLE
error in connection to bazzar

### ISSUE THREAD

**Issue by arnouir** [cafebazaar/Poolakey#31]
`    java.lang.NoSuchMethodError: No direct method <init>(ILjava/lang/Object;Ljava/lang/Class;Ljava/lang/String;Ljava/lang/String;I)V in class Lkotlin/jvm/internal/FunctionReferenceImpl; or its super classes (declaration of 'kotlin.jvm.internal.FunctionReferenceImpl' appears in /data/app/ir.b3b.vocabbox-1s3XfAF1nTv2n9hYJuWnEA==/base.apk)
        at ir.cafebazaar.poolakey.BillingConnection$startConnection$1.<init>(Unknown Source:10)
        at ir.cafebazaar.poolakey.BillingConnection.startConnection$poolakey_release(BillingConnection.kt:44)
        at ir.cafebazaar.poolakey.Payment.connect(Payment.kt:68)`

this error occurs when trying to connect to bazzar with below code :
`    paymentConnection = payment.connect {
      connectionSucceed {
      }
      connectionFailed {
      }
      disconnected {
      }
    }`

version : alpha08

**Comment by shayanpourvatan** [comment]
Do you have another `AIDL` file in your project?

**Comment by alialavi1** [comment]
Hi dear shayan.
Hope poolaky solve all error in iap.
But there are a question. We use one aidl in project for all stores, only we change some parameter for switch to each one. Finally we get release for all store by set some flag  regard to stores 
If poolkey work in cafe bazaar only. And existance an another Aidl is imposible what can i do?

May be poolaky can use for othere stores. 

Have you any information?

**Comment by shayanpourvatan** [comment]
Hi Ali.
I don't get your last sentence, but, you can't work with one AIDL file for multiple store, Please read more about AIDL file and method ordering in it. As method order and method signature is mattered for the AIDL file, You must have one payment module for each store you have.

**Comment by hemmaty76** [comment]
why is issue closed? !!
I have this problem too
I use just bazar  AIDL

**Comment by alialavi1** [comment]
سلام اره میگه نفهمیدم منظورتون چیه از 1 iadl و چند تا فروشگاه
قبلا 4 تا فروشگاه را با یه دونه فعال کردم و مشکلی هم نبود .
ولی داره منسوخ میشه .
پرسیدم ازش که پولکی را میشه برای چند تا فروشگاه تنظیم کرد که پیچوند و جواب
درست نداد

**Comment by shayanpourvatan** [comment]
@hammaty76 Could you explain your issue? When you got error? please post your logcat too.

**Comment by shayanpourvatan** [comment]
@alialavi1 به خاطر تغییراتی که در فایل ارتباطی افتاده امکان استفاده از یک فایل برای چنتا فروشگاه وجود نداره و باید مکانیزم دیگری برای حل این مشکل پیدا کنید. این که پولکی رو می‌تونین برای فروشگاه‌های دیگه هم استفاده کرد رو اطلاع دقیقی ندارم، ولی رسالت اصلی این لایبرری استفاده از پرداخت بازار هست و مسئولیتی رو پرداخت دیگر فروشگاه‌ها ندارد.
