### ISSUE TITLE
only on Huawei p10 lite, getPurchasedProducts' result is an empty list

### ISSUE THREAD

**Issue by hadi72h** [cafebazaar/Poolakey#33]
**Describe the bug**
Only on the Huawei p10 lite.
after paid on Bazaar, we receive an empty list in getPurchasedProducts' result.
I tried on multiple devices, on their everything is ok, but the Huawei p10 lite.

**Versions**
- Version of the library that your are using: 1.0.0-alpha08

**Comment by shayanpourvatan** [comment]
Please use our latest version, If you are faced with the same problem,Please open this issue and post more detail about your error
