### ISSUE TITLE
مشکل در TargetSdk 11

### ISSUE THREAD

**Issue by vd92** [cafebazaar/Poolakey#45]
متاسفانه کتابخانه با `targetsdk 11` سازگار نیست و با توجه به منقضی شدن `onActivityResult ` نمی‌توان از آن استفاده نمود

**Comment by shayanpourvatan** [comment]
ممنون میشم خطایی که در اندروید ۱۱ میگیرین رو بگین، همچنین ورژن نسخه‌ای که استفاده میکنین
