### ISSUE TITLE
<< Get all products for show price of those before buy it inside app itself >>

### ISSUE THREAD

**Issue by mhrohani1385** [cafebazaar/Poolakey#52]
**Describe the bug**
This library can't provide get all products for show price of those before buy it inside app itself **(Querying for Items Available for Purchase)**

**Expected behavior**
As you can get purchases product , *get all products with details* must be implemented
Like Java Payment API : https://developers.cafebazaar.ir/en/guidelines/in-app-billing/implementation/java#iab_class ->  
   Querying for Items Available for Purchase

**Versions**
- Version of the library that your are using: 1.2.2

**Comment by shayanpourvatan** [comment]
As you can see in our sample project, we have two function for getting the product info:

`payment.getInAppSkuDetails`, `payment.getSubscriptionSkuDetails`.

For more info please see the [MainActivity](https://github.com/cafebazaar/Poolakey/blob/master/app/src/main/java/ir/cafebazaar/poolakeysample/MainActivity.kt) in the sample project.

**Comment by mhrohani1385** [comment]
Thank You !
