### ISSUE TITLE
عدم پشتیبانی از Jetpack Compose

### ISSUE THREAD

**Issue by vd92** [cafebazaar/Poolakey#53]
سلام
من نرم افزار جدیدم رو کاملا بر پایه رو کامپوز نوشتم اما متاسفانه کتابخونه با اون سازگار نیست. ممنون میشم این مورد رو هم اضافه کنید

**Comment by msmoradi** [comment]
سلام 
اگه بیشتر توضیح بدید که به چه مشکلی برخوردید  و منظورتون از سازگار نیست  چیه  ، بهتر میتونیم کمک کنیم .
ممنون

**Comment by DHosseiny** [comment]
شاید منظورشون اینه که چیزایی مثل state در کامپوز هماهنگ نیست. باید بگم اینجا توضیح داده چطور  observableهای rxjava رو به compose state تبدیل کنیم.
https://developer.android.com/jetpack/compose/state#use-other-types-of-state-in-jetpack-compose
