### ISSUE TITLE
onActivityResult is deprecated

### ISSUE THREAD

**Issue by Albul** [cafebazaar/Poolakey#57]
Hi, we need a new mechanism to get notified about purchase success or failure.

![image](https://user-images.githubusercontent.com/1837809/141800211-4cfb1e5b-6a3e-451c-b431-c41cd010adbc.png)

Please read this thread https://stackoverflow.com/questions/62671106/onactivityresult-method-is-deprecated-what-is-the-alternative
Is it possible to add needed callbacks right to `callback: PurchaseIntentCallback.() -> Unit` ?

**Comment by msmoradi** [comment]
Thanks for reporting this issue. it will be added in future release of this library.

**Comment by msmoradi** [comment]
Fixed now in [2.0.0](https://github.com/cafebazaar/Poolakey/releases/tag/2.0.0)
