### ISSUE TITLE
IInAppBillingService$Default is defined multiple times

### ISSUE THREAD

**Issue by sajjadroudi** [cafebazaar/Poolakey#62]
باسلام
ما در اپی که داریم از پرداخت درون برنامه ای مایکت و کافه بازار استفاده می کنیم.
با مهاجرت به پولکی مشکلی در خروجی release گرفتن پیش آمد و چنین اروری توسط gradle نمایش داده می شود.
 
Type com.android.vending.billing.IInAppBillingService$Default is defined multiple times: C:\Users\Roudi\.gradle\caches\transforms-3\34dd8bb88a71d0c96e70d6e7721fb778\transformed\jetified-poolakey-1.3.0-runtime.jar:com/android/vending/billing/IInAppBillingService$Default.class, D:\dev\workspace\myproject\app\build\intermediates\asm_instrumented_project_classes\cafe_bazaarRelease\com\android\vending\billing\IInAppBillingService$Default.class

وقتی فایل C:\Users\Roudi\.gradle\caches\transforms-3\34dd8bb88a71d0c96e70d6e7721fb778\transformed\jetified-poolakey-1.3.0-runtime.jar حذف می شود، بیلد signed apk با موفقیت صورت میگیرد ولی وقتی در اپ کاربر به آنجایی که از پرداخت درون برنامه ای استفاده شده است، منتقل می شود، برنامه کرش می کند.

لطفا این موضوع را بررسی فرمایید.

**Comment by msmoradi** [comment]
سلام
تو روش قبلی نیاز بود که فایل 
IInAppBillingService.aidl
رو به پروژه خودتون اضافه کنید که با مهاجرت با پولکی دیگه نیاز نیست .
لطفا اون فایل رو از پروژه حذف کنید و مجدد امتحان کنید .

**Comment by sajjadroudi** [comment]
بله درست شد. خیلی ممنونم.
