### ISSUE TITLE
The integration documentation is out of date

### ISSUE THREAD

**Issue by Husseinhj** [cafebazaar/Poolakey#66]
Integration documentation is totally wrong and hasn't been updated with breaking changes.
I'm using the latest version of the library (v2.0.0).

Please review your [integration documentation](https://developers.cafebazaar.ir/en/guidelines/in-app-billing/implementation/kotlin#build
) and fix these errors:

1- `subscribeProduct`:

Incorrect:
```kotlin
payment.subscribeProduct(activity = this, request = purchaseRequest) {...}
```

Correct
```kotlin
fun purchaseProduct(
        registry: ActivityResultRegistry,
        request: PurchaseRequest,
        callback: PurchaseCallback.() -> Unit
    ) {
```

2- `PurchaseRequest`

Incorrect:
```kotlin
val purchaseRequest = PurchaseRequest(
    productId = "subscriptionProduct",
    requestCode = 1234,
    payload = ""
)
```

Correct:
```kotlin
data class PurchaseRequest(
    val productId: String,
    val payload: String? = null,
    val dynamicPriceToken: String? = null
)
```

3- `onActivityResult`:

No longer exists:
```kotlin
payment.onActivityResult(requestCode, resultCode, data) {...}
```

**Comment by msmoradi** [comment]
Hi @Husseinhj,
Thanks for reporting, These issues will be fixed as soon as possible.

**Comment by Husseinhj** [comment]
Hi @msmoradi 

Thanks for your swift response.
I see that you made several changes that affected developers who would like to migrate from your old to your new library. It would be helpful if you would provide migration documentation on the website.

**Comment by msmoradi** [comment]
Fixed
