### ISSUE TITLE
Could not find com.github.cafebazaar.Poolakey:poolakey:latest_version.

### ISSUE THREAD

**Issue by vahidvb** [cafebazaar/Poolakey#67]
Could not find com.github.cafebazaar.Poolakey:poolakey:latest_version.
Required by:
    project :app
Search in build.gradle files

**Comment by msmoradi** [comment]
@vahidvb 
You should replace latest_version part with a specific version of poolakey,
https://github.com/cafebazaar/Poolakey/releases

**Comment by vahidvb** [comment]
I try all versions but same result :

Could not find com.github.cafebazaar.Poolakey:poolakey:2.0.0.
Required by:
    project :app
Search in build.gradle files

**Comment by vahidvb** [comment]
I found myself after hours
add maven { url 'https://www.jitpack.io' } in settings.gradle not just in build.gradle
