### ISSUE TITLE
استفاده از پولکی در کتابخانه LibGDX

### ISSUE THREAD

**Issue by CoderoidAcademy** [cafebazaar/Poolakey#69]
سلام ، وقت بخیر

بنده میخوام پولکی رو روی یه بازی که با libgdx نوشتم، پیاده کنم. اکتیویتی ای که باید پولکی رو مدیریت کنه حتما باید از 

`com.badlogic.gdx.backends.android.AndroidApplication`

ارث بری کنه.این کلاس نیز از `Activity` ارث بری میکنه نه `AppCompatActivity`. بخاطر همین در این متد

`payment.purchaseProduct(
registry = activityResultRegistry,
request = purchaseRequest)`

نمیتونم `activityResultRegistry` رو بگیرم. چون این نمونه فقط توی `AppCompatActivity` هستش.

درواقع برای استفاده از پولکی توی فریموورک LibGDX این مشکل برای همه پیش میاد.
لطفا راهنمایی کنید.

**Comment by shayanpourvatan** [comment]
سلام.

از ورژن ۱.۳.۰ ( ورژن قبلی لایبرری ) می‌تونین استفاده کنین.

**Comment by hamidrezasahraei** [comment]
@CoderoidAcademy 
از کدوم نسخه‌ی LibGDX استفاده می‌کنین؟

**Comment by DHosseiny** [comment]
به نظر میرسه بیشتر مشکل LibGDX باشه و اینکه ما از ComponentActivity استفاده میکنیم که پاییه ترین activity ممکنی هست که activityResultRegistry رو داره. من closeش میکنم ولی اگر حس میکنید مشکل libray ماست لطفا کامنت بزارید تا رسیدگی کنیم.
