### ISSUE TITLE
باز نشدن صفحه پرداخت

### ISSUE THREAD

**Issue by rasoulisaeid** [cafebazaar/Poolakey#70]
سلام. من کتابخونه رو به پروژه م که با زبان جاوا هست اضافه کردم و پیاده کردم، لاگ می گیرم purchaseFlowBegan انجام میشه ولی صفحه ای باز نمیشه. نباید BottomSheetDialogFragment بازار باز بشه؟

**Comment by radeshf** [comment]
من هم مشکل مشابه رو دارم. وارد هیچ خطایی نمیشه ولی صفحه ای هم از پرداخت بازار باز نمیشه

**Comment by radeshf** [comment]
دوست عزیز من این مورد رو برای خودم حل کردم شاید به شما هم کمک کنه و تیم پولکی هم توی داکیومنتش تاکید کنه روش

به نظر میاد اگه از فرگمنت یا دیالوگ بخواید پرداخت رو انجام بدید صفحه باز نمیشه و خطایی هم داده نمیشه پس بهتره یا توی اکتیویتی پرداخت رو انجام بدید یا اینکه حواستون باشه اکتیویتی والد فرگمنت حتما حتما از AppCompatActivity ارث بری کرده باشه. یه نمونه کد هم میزارم که بهتر مشخص باشه

`val payment = Payment(context = requireActivity() as AppCompatActivity, config = paymentConfig)`

برای activityResultRegistry هم از کد زیر استفاده کنید

`payment?.purchaseProduct(registry = (requireActivity() as AppCompatActivity).activityResultRegistry, request = purchaseRequest)`

**Comment by shayanpourvatan** [comment]
سلام.
از چه ورژنی از پولکی استفاده میکنید؟
ممنون میشم تیکه کدی که دارین پرچیس رو فراخوانی میکنین ارسال کنین.

**Comment by esirahimian** [comment]
من هم مشکل مشابه دارم و این ارور میاد
we can't communicate with bazzar service is ddisconnected

**Comment by ranjbarhadi** [comment]
یه باگ کوچیک در کد هست که منجر میشه هیچ کدوم از کال بک‌ها جوابی دریافت نکنه مخصوصا کال بک شکست در اتصال. من یه پول رکوئست فرستادم و مشکل رو حل کردم. البته. یک باگ دیگه وجود داره که برنامه نمیتونه به بازار وصل بشه. باید برنامه بازار رو یکبار باز کنید و بعد مجددا اکتیویتی برنامه خودتون رو باز کنید. 
https://github.com/cafebazaar/Poolakey/pull/73

**Comment by eldorado** [comment]
سلام. منم همین مشکل رو دارم.
من هم توی فرگمنت دارم فراخوانی میکنم. متاسفانه توی api 33 درست کار نمیکنه و کال بک جوابی برنمیگردونه. و برنامه کرش میکنه.
روش هایی که گفته شد رو همه رو رفتم. جالب اینجاست که با حذف و نصب کافه بازار، مشکل حل میشه (بدون اینکه برنامه خودم رو هیچ تغییری بدم). با نصب مجدد کافه بازار، مشکل رفع میشه اما بعد از یکی دو روز مجددا کال بک جوابی برنمیگردنه (بازم بدون اینکه برنامه رو هیچ تغییر بدم) و برنامه بازم کرش میکنه

**Comment by ranjbarhadi** [comment]
@eldorado من این مشکل رو حل کردم. بنظرم از ریپوی من استفاده کن 
متاسفانه بچه‌های کافه بازار درخواست pull request منو بررسی نکردن و بنظرم خیلی ها با این شکل درگیر هستند. اینجا میتونی توضیحاتش رو بخونی :
https://github.com/cafebazaar/Poolakey/pull/73
همچنین رپوی منو میتونی از اینجا دانلود کنی:
https://github.com/ranjbarhadi/Poolakey

**Comment by eldorado** [comment]
# @ranjbarhadi ممنونم
من مطلبی که گفتید رو قبلا خونده بودم و تست کرده بودم. توی api 33 متاسفانه اون روشی که گفتید رو تست کرده بودم، ولی جواب نمیداد و بازم کرش میکرد. البته من روی دیوایس واقعی تست نکردم. تست من روی ایمولاتور خود اندروید استودیو هست.

**Comment by DHosseiny** [comment]
@AlirezaSoltaniJazi Can you please test poolakey on api 33?

**Comment by DHosseiny** [comment]
دوستان ما روی api 33 تست کردیم و مشکلی نداشتیم. اگر ممکنه با ورژن آخر پولکی تست بفرمایید، اگر مشکلی بود لطفا با ارسال کد بهمون کمک کنید که reproduce ش کنیم مشکل رو. ممنون

**Comment by mostafamoradi2022** [comment]
استاد باز نمیشه .اندروید 11 سامسونگ a20 
جاوا کد-api33

**Comment by mostafamoradi2022** [comment]
activityResultRegistry = this.getActivityResultRegistry();
  
  از این توی اکتیوتی استفاده کردم اوکی شد

**Comment by DHosseiny** [comment]
مصطفی لطفا روش حل رو بیشتر توضیح میدی؟ ما توی پولکی جایی نیاز به activityResultRegistry نداریم.

**Comment by hamid97m** [comment]
از اونجایی که خیلی وقت هستش این ترد باز هست و پاسخی دریافت نشده این ایشو رو ما میبندیم، اگه هرگونه مشکلی داشتین ممنون میشیم با ما در میون بزارین
