### ISSUE TITLE
Could not find com.github.cafebazaar.Poolakey:poolakey:2.0.0.

### ISSUE THREAD

**Issue by mahdizareeii** [cafebazaar/Poolakey#71]
Execution failed for task ':app:checkCafebazaarDebugAarMetadata'.
> Could not resolve all files for configuration ':app:cafebazaarDebugRuntimeClasspath'.
   > Could not find com.github.cafebazaar.Poolakey:poolakey:2.0.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/github/cafebazaar/Poolakey/poolakey/2.0.0/poolakey-2.0.0.pom
       - https://repo.maven.apache.org/maven2/com/github/cafebazaar/Poolakey/poolakey/2.0.0/poolakey-2.0.0.pom
     Required by:
         project :app
وی پی ان هم زدم :)

**Comment by shayanpourvatan** [comment]
you need to add jitpack as your maven repository in build.gradle file like following:

```
repositories {
        google()
        jcenter()
        maven { url 'https://jitpack.io' }
    }
```

**Comment by mahdizareeii** [comment]
i added this too but the android studio can download the dependency

**Comment by mahdizareeii** [comment]
create new project and add the dependency : 
`implementation "com.github.cafebazaar.Poolakey:poolakey:2.0.0"`
and add the jitpack as your maven repository in build.gradle : 
`repositories {
        google()
        jcenter()
        maven { url 'https://jitpack.io' }
}`
your project will be sync without any problem, but the project can not find the class of the library, and when you want to rebuild your project you will give the error that i said first

**Comment by mahdizareeii** [comment]
pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
        jcenter()
        maven { url 'https://jitpack.io' }
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        jcenter()
        maven { url 'https://jitpack.io' }
    }
}

**Comment by ariashahdadi** [comment]
we had the same issue, we fixed it as [mahdizareeii](https://github.com/mahdizareeii) said you need to add jitpack to your [settings.gradle]() 
```gradle
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        jcenter() // Warning: this repository is going to shut down soon
    }
}
```
