### ISSUE TITLE
Could not resolve com.github.cafebazaar.Poolakey:poolakey:2.0.0.

### ISSUE THREAD

**Issue by dariushEm** [cafebazaar/Poolakey#72]
dependencies {
    implementation "com.github.cafebazaar.Poolakey:poolakey:2.0.0"
}

**Comment by shayanpourvatan** [comment]
Possible duplicate with #71

**Comment by dariushEm** [comment]
> Possible duplicate with #71

what???????????

**Comment by shayanpourvatan** [comment]
Please see the following link:

https://github.com/cafebazaar/Poolakey/issues/71

We think this issue is duplicate with old issue.

**Comment by farhadrazzaghi** [comment]
duplicate with old issue. https://github.com/cafebazaar/Poolakey/issues/71
