### ISSUE TITLE
مشکل در پرداخت 

### ISSUE THREAD

**Issue by 75q399996666n** [cafebazaar/Poolakey#74]
برای من فقط یک صفحه ی سفید بدون هیچ اروری باز میشه واقعا مشکلش چیه ؟

**Comment by 75q399996666n** [comment]
![pament error1](https://user-images.githubusercontent.com/104717609/193447751-8c5853e5-8ce3-4fc9-982a-3aebf32ef522.JPG)
![pament errror2](https://user-images.githubusercontent.com/104717609/193447771-5dbbc046-0d20-490d-8b03-a54f47c70275.JPG)
![pament error3](https://user-images.githubusercontent.com/104717609/193447777-7f0c3f2f-1d94-49b7-888d-c4933e3891a2.JPG)
![payment error4](https://user-images.githubusercontent.com/104717609/193447786-6dfaa9da-a24e-4383-b038-5043b9a2c744.JPG)
![libpoolaki](https://user-images.githubusercontent.com/104717609/193447796-dd5b4bca-23d8-4a19-ac37-8309007bda3b.JPG)
![sfdagdg](https://user-images.githubusercontent.com/104717609/193447799-7c8b860c-8c33-46bd-872a-c5142513274a.JPG)
سلام اینم اسکرین کد هام هستش که گزاشتم راستش اروری نشون نمیده و فقط یه صفحه سفید باز میشه پیغام great رو نشون میده و بعدشم پیغام failed to buy در همین حد هیچ صفحه ی پرداخت و اینا نشون نمیده برنامم رو تو کافه بازار اپلود کردم برای تست پرداخت درون برنامه ای و هنوز انتشار عمومی نکردمم  خواستم تست درون برنامه ایش رو تست کنم که طبق مستندات خود بازار رفتم اما برنامم درست کار نکرد و نمیدونم چجوری باید درستش کنم  بعد پروژه ی من به زبان جاوا بودش و قسمت اکتیویتی پرداخت رو فقط میخواستم با کاتلین برم اما بعدا یه پروزه ی کاتلین هم باز کردم اونجا هم تست کردم همین مشکل رو داشت و فقط یه صفحه سفید باز میشه همین

**Comment by shayanpourvatan** [comment]
لطفا مقدار throwable رو لطفا لاگ بگیرین و ببینین ارور چی هست.

**Comment by 75q399996666n** [comment]
انجام دادم ولی اروری نشون نداد

**Comment by akhanifar** [comment]
منم موقع پرداخت با خطای زیر مواجه میشم.
The purchase was hijacked and it's not a valid purchase.
 با کد نویسی جاوا بدون هیچ مشکلی انجام میشه ولی با کاتلین با این خطا مواجه میشم.

**Comment by 75q399996666n** [comment]
> منم موقع پرداخت با خطای زیر مواجه میشم. The purchase was hijacked and it's not a valid purchase. با کد نویسی جاوا بدون هیچ مشکلی انجام میشه ولی با کاتلین با این خطا مواجه میشم.

شما همون پولکی رو با زبان جاوا نوشتین ؟ 
میشه کدهارو به اشتراک بزارین یا به ایمیلم بفرستین ؟ میخوام با جاوا هم تست کنم ببینم کار میکنه یا نه

**Comment by akhanifar** [comment]
> > منم موقع پرداخت با خطای زیر مواجه میشم. The purchase was hijacked and it's not a valid purchase. با کد نویسی جاوا بدون هیچ مشکلی انجام میشه ولی با کاتلین با این خطا مواجه میشم.
> 
> شما همون پولکی رو با زبان جاوا نوشتین ؟ میشه کدهارو به اشتراک بزارین یا به ایمیلم بفرستین ؟ میخوام با جاوا هم تست کنم ببینم کار میکنه یا نه

پولکی رو با زبان کاتلین تست کردم (مشکلم برطرف شد). زبان جاوا با [TrivialDrive](https://github.com/cafebazaar/TrivialDrive) و آموزش خود کافه بازار کار کردم.

**Comment by 75q399996666n** [comment]
> > > منم موقع پرداخت با خطای زیر مواجه میشم. The purchase was hijacked and it's not a valid purchase. با کد نویسی جاوا بدون هیچ مشکلی انجام میشه ولی با کاتلین با این خطا مواجه میشم.
> > 
> > 
> > شما همون پولکی رو با زبان جاوا نوشتین ؟ میشه کدهارو به اشتراک بزارین یا به ایمیلم بفرستین ؟ میخوام با جاوا هم تست کنم ببینم کار میکنه یا نه
> 
> پولکی رو با زبان کاتلین تست کردم (مشکلم برطرف شد). زبان جاوا با [TrivialDrive](https://github.com/cafebazaar/TrivialDrive) و آموزش خود کافه بازار کار کردم.


من پرداخت پولکی کاتلین رو تست کردم کار نکرد یعنی خودم پروژه کاتلین باز کردم فقط پرداخت پولکی تست کردم ولی کار نکرد اگر بفرستم میتونین بهش یه نگاه بندازین

**Comment by farhadrazzaghi** [comment]
سلام روز بخیر باشه با توجه به اسکرین شات ها کد ها درست به نظر میاند . اما نکاه ایی که به نظر مشکل میاد نحوه شروع فرایند خرید هست . پیشنهاد می کنم که برای تست کد های مربوط به init کردن فرایند پرداخت رو در همون onCreate پیاده سازی کنید ولی کد های مربوط به شروع فرایند پرداخت رو به یک onClickListener مثلا برای یک دکمه در اکتیویتی خودتون منتقل کنید . برای اینکه بتونیم بهتر به حل مشکل شما کمک کنیم خوشحال میشم که کد های خودتون رو با ما به اشتراک بذارید.

**Comment by 75q399996666n** [comment]
> سلام روز بخیر باشه با توجه به اسکرین شات ها کد ها درست به نظر میاند . اما نکته ایی که به نظر مشکل میاد نحوه شروع فرایند خرید هست . پیشنهاد می کنم که برای تست کد های مربوط به init کردن فرایند پرداخت رو در همون onCreate پیاده سازی کنید ولی کد های مربوط به شروع فرایند پرداخت رو به یک onClickListener مثلا برای یک دکمه در اکتیویتی خودتون منتقل کنید . برای اینکه بتونیم بهتر به حل مشکل شما کمک کنیم خوشحال میشم که کد های خودتون رو با ما به اشتراک بذارید.

**Comment by 75q399996666n** [comment]
> سلام روز بخیر باشه با توجه به اسکرین شات ها کد ها درست به نظر میاند . اما نکته ایی که به نظر مشکل میاد نحوه شروع فرایند خرید هست . پیشنهاد می کنم که برای تست کد های مربوط به init کردن فرایند پرداخت رو در همون onCreate پیاده سازی کنید ولی کد های مربوط به شروع فرایند پرداخت رو به یک onClickListener مثلا برای یک دکمه در اکتیویتی خودتون منتقل کنید . برای اینکه بتونیم بهتر به حل مشکل شما کمک کنیم خوشحال میشم که کد های خودتون رو با ما به اشتراک بذارید.

سلام من مشکل پرداختم رو حل کردم خیلی ممنون از پاسختون
