### ISSUE TITLE
  مشکل در خرید  اشتراک پولکی

### ISSUE THREAD

**Issue by haleop** [cafebazaar/Poolakey#84]
بعد از خرید اشتراک باز هم صفحه خرید برای کاربر باز میشه به جایی اینکه صفحه " شما این محصول را خریذاری کردین

**Comment by hamid97m** [comment]
میتونی سناریو دقیق تری را برامون بگی؟ یه سناریو که ممکنه این تفاق بیفته اینه که کاربر با شماره دیگه‌ای تو بازارش لاگین کنه به طور مثال
