### ISSUE TITLE
consumePurchasedItem()

### ISSUE THREAD

**Issue by haleop** [cafebazaar/Poolakey#85]
consume انجام نمیشود

**Comment by DHosseiny** [comment]
مشکلتون چیه؟ ما تست کردیم و مشکلی نداشتیم. میتونیم کد سمپل بفرستید؟

**Comment by hamid97m** [comment]
از اونجایی که خیلی وقت هستش این ترد باز هست و پاسخی دریافت نشده این ایشو رو ما میبندیم،  اگه مشکلی داشتین با ما در میون بزارین
