### ISSUE TITLE
مشکل چرخش اتوماتیک صفحه در حال پرداخت بازی

### ISSUE THREAD

**Issue by AlirezaTabasi7** [cafebazaar/Poolakey#86]
وقتی در حال خرید در صفحه اکتیویتی بازار هستیم اگر به هر دلیلی گوشی بچرخه اکتویتی کافه بازار ریست میشه و کاربر باید خریدش رو از اول انجام بده و این تجربه بدی برای کاربر رقم میزنه.

خوبه امکانی وجود داشته باشه که بشه چرخش صفحه رو قفل کرد روی یک حالت خاصی.
من میدونم که توی مانیفست اکتویتی میشه عبارت android:screenOrientation="portrait" گذاشت و اینکارو انجام داد ولی وقتی داریم با پلاگین پولکی کار میکنیم مستقیما کنترلی روی اکتیویتی کافه بازار نداریم.
برای اینکار باید چه اقداماتی صورت بگیره؟
پیشاپیش متشکرم.

**Comment by DHosseiny** [comment]
ما به این مشکل توی پرداخت نخوردیم @AlirezaTabasi7 . فقط توی درگاه پرداخت اگه اطلاعاتی نوشته باشه و روتیت کنه نوشته هاش پاک میشه. اگه غیر از این منظورته سناریوی خاصی داره؟ میشه ویدئویی ازش برامون بفرستی؟

**Comment by AlirezaTabasi7** [comment]
توی ویدئویی که لینکشو در ادامه میفرستم کاملا مشخصه منظورم و با صدا ببینید لطفا:

https://drive.google.com/file/d/1XBT47xti4cryKzTkNHx8KG4Jn2uScTnp/view?usp=sharing

(برای گرفتن دسترسی ویدئو درخواست بفرستید لطفا)

**Comment by hamid97m** [comment]
> توی ویدئویی که لینکشو در ادامه میفرستم کاملا مشخصه منظورم و با صدا ببینید لطفا:
> 
> https://drive.google.com/file/d/1XBT47xti4cryKzTkNHx8KG4Jn2uScTnp/view?usp=sharing
> 
> (برای گرفتن دسترسی ویدئو درخواست بفرستید لطفا)

ممنون میشیم دسترسی به ویدیو رو بدین لطفا روی درایو

**Comment by DHosseiny** [comment]
اسم برنامه تون، پکیج نیم تون، گوشیی که روش تست میشه و ورژن اندرویدش  رو لطفا بفرستید.

**Comment by AlirezaTabasi7** [comment]
اسم: سلطان تخته نرد
پکیج نیم: backgammon.onlinegame.dice.hokm
یکی از گوشی هایی که روش تست میشه: Samsung A21s
اندروید 12

**Comment by AlirezaTabasi7** [comment]
سلام با توجه به گذشت 1 ماه میخواستم ببینم پیشرفتی روی حل این مشکل داشتیم؟
یا بصورت کلی اصلا مشکل تایید و توی بک لاگ شما تعریف شده؟

**Comment by AlirezaTabasi7** [comment]
سلام با توجه به گذشت 1 ماه میخواستم ببینم پیشرفتی روی حل این مشکل داشتیم؟
یا بصورت کلی اصلا مشکل تایید و توی بک لاگ شما تعریف شده؟

@DHosseiny @hamid97m

**Comment by DHosseiny** [comment]
داریم روش کار میکنم @AlirezaTabasi7

**Comment by DHosseiny** [comment]
علیرضا شما از پولکی یونیتی استفاده میکنید که داکش [اینجاست](https://developers.cafebazaar.ir/fa/guidelines/in-app-billing/implementation/unity-2) یا همین پروژه پولکی؟ گیت هاب اون پروژه [اینجاست](https://github.com/cafebazaar/PoolakeyUnitySdk). میخوام بدونم اگر اون هست همون sdk رو تست کنیم. @AlirezaTabasi7

**Comment by AlirezaTabasi7** [comment]
بله ما از پولکی مخصوص یونیتی استفاده میکنیم که لینک اول شما یعنی [https://developers.cafebazaar.ir/fa/guidelines/in-app-billing/implementation/unity-2](اینجاست)

**Comment by AlirezaTabasi7** [comment]
سلام.
پیشرفتی روی این تسک انجام شده؟
 @DHosseiny @hamid97m

**Comment by DHosseiny** [comment]
بله مشکل از پولکی یونیتی هست. اینجا رفته جلو:
https://github.com/cafebazaar/PoolakeyUnitySdk/pull/13

**Comment by DHosseiny** [comment]
دان شد در PoolakeyUnity ورژن جدید دادیم.
https://github.com/cafebazaar/PoolakeyUnitySdk/releases/tag/2.1.0
