### ISSUE TITLE
An exception was thrown for pulling subscribe history when you are not logged in to the bazaar appstore

### ISSUE THREAD

**Issue by gpandroid1990** [cafebazaar/Poolakey#90]
Hello developer, in our application, there is a logic to determine whether the current account has a historical subscription record before subscribing to a product.
If there is, it will prompt that you cannot subscribe again; if there is not, you can start subscribing. During my test, if bazaar appstore has no problem with normal login,
However, if the bazaar appstore is not logged in, an error will be thrown when pulling the history record ir.cafebazaar.poolakey.exception.ResultNotOkayException: Failed to receive response from Bazaar. If you subscribe directly, the login interface will pop up to allow the user to log in to the bazaar appstore. operate,
I would like to ask how to detect whether bazaar appstore is logged in in my application. If not, can I call a method to jump to the bazaar appstore login page?

**Comment by DHosseiny** [comment]
The flow can go through this way: 
1. first, ask for history records. 
2. If the exception happened treat it as user is not logged in and call the subscribe function in the payment class.
Tell me if it does not meet your requirements or not working the way you expected.
